# Generated by Django 5.2.8 on 2025-12-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
